### ISSUE TITLE
alpine DNS issues

### ISSUE THREAD

**Issue by travisghansen** [nmaupu/freenas-provisioner#11]
I'm seeing the issues exhibited here: https://github.com/gliderlabs/docker-alpine/issues/255

We may consider using an image that isn't musl based until they figure it out..

**Comment by nmaupu** [comment]
I propose using minideb instead of alpine from now on.
https://github.com/nmaupu/freenas-provisioner/pull/15

**Comment by travisghansen** [comment]
Good call.
