### ISSUE TITLE
Interested in building out iscsi provisioning?

### ISSUE THREAD

**Issue by travisghansen** [nmaupu/freenas-provisioner#2]
This is pretty cool...looks similar to the nfs-client provisioner but probably better handles size limits.  Any interest in working out the provisioner to also support block storage and return iscsi volumes?  I'd be interested in helping.

**Comment by nmaupu** [comment]
Hey,

That's a good idea indeed, I didn't try it yet because of lack of time right now but feel free to PR it if you want !

**Comment by travisghansen** [comment]
Looking through the code it doesn't appear you're setting a quote on the datasets, is that correct?

**Comment by nmaupu** [comment]
By quote, you mean a comment ?

**Comment by travisghansen** [comment]
Sorry, quota.. typing on a phone :(

**Comment by nmaupu** [comment]
I didn't support quota indeed (can we using NFS ?)

**Comment by travisghansen** [comment]
Well, since you're creating a dataset per share, I think it's possible.  You set it on the dataset.

**Comment by travisghansen** [comment]
So I've just tested this out and confirmed it works nicely.  If you create a dataset and put a quota on it and then subsequently mount the associated nfs share, `df` etc actually show the appropriate amount of available space.  Furthermore, if you subsequently update the dataset quota, it's reflected immediately on mounted filesystems.

With that in mind, this plugin (as opposed to the generic `nfs-client` provisioner becomes much more compelling.  One issue I see is permissions on the folder/share initially.  The `nfs-client` provisioner does a chmod 777 on the parent directory so the container can write to it regardless of what user the container is running as.  Seems like something similar would be required to make it truly useful for containers running as non-root.

**Comment by travisghansen** [comment]
@nmaupu on this one, what are your thoughts?  Should this be a separate project altogether?  I know there will be some shared code but I hate to 'muddy the waters' too much.  I also don't think it wise to make the single binary handle both styles (ie: adding a required parameter to the storage class to indicate).  Any high-level thoughts before I start moving on this?

**Comment by travisghansen** [comment]
Building this out as a second project.  Closing this.
