### ISSUE TITLE
crash when creating PV in OKD3.11

### ISSUE THREAD

**Issue by gripenk** [nmaupu/freenas-provisioner#25]
FreeNAS-11.2-U5
OpenShift Master:
v3.11.0+f8b6451-269
Kubernetes Master:
v1.11.0+d4cacc0
OpenShift Web Console:
v3.11.0+ea42280

freenas-provisioner:v2.4

Created a PV (any size), POD of freenas-nfs-provisioner crashed with the following log 

I0819 09:50:33.675241       1 leaderelection.go:187] attempting to acquire leader lease  kube-system/freenas.org-nfs...
--
  | I0819 09:50:51.079613       1 leaderelection.go:196] successfully acquired lease kube-system/freenas.org-nfs
  | I0819 09:50:51.079725       1 controller.go:571] Starting provisioner controller freenas.org/nfs_freenas-nfs-provisioner-597d5b54ff-b5h5q_c9a12f6a-c266-11e9-ab40-0a580a830207!
  | I0819 09:50:51.080589       1 event.go:221] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"kube-system", Name:"freenas.org-nfs", UID:"9feece69-c265-11e9-af03-005056837f20", APIVersion:"v1", ResourceVersion:"623006", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' freenas-nfs-provisioner-597d5b54ff-b5h5q_c9a12f6a-c266-11e9-ab40-0a580a830207 became leader
  | I0819 09:50:51.179903       1 controller.go:620] Started provisioner controller freenas.org/nfs_freenas-nfs-provisioner-597d5b54ff-b5h5q_c9a12f6a-c266-11e9-ab40-0a580a830207!
  | I0819 09:50:51.180060       1 controller.go:926] provision "kube-system/k1" class "freenas-nfs": started
  | E0819 09:50:51.183384       1 runtime.go:69] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
  | /home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
  | /home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
  | /home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
  | /home/travis/.gimme/versions/go1.10.5.linux.amd64/src/runtime/asm_amd64.s:573
  | /home/travis/.gimme/versions/go1.10.5.linux.amd64/src/runtime/panic.go:502
  | /home/travis/.gimme/versions/go1.10.5.linux.amd64/src/runtime/panic.go:63
  | /home/travis/.gimme/versions/go1.10.5.linux.amd64/src/runtime/signal_unix.go:388
  | /home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/provisioner/provisioner.go:243
  | /home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller/controller.go:1014
  | /home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller/controller.go:786
  | /home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller/controller.go:759
  | /home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller/controller.go:683
  | /home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller/controller.go:697
  | /home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller/controller.go:657
  | /home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller/controller.go:616
  | /home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
  | /home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
  | /home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
  | /home/travis/.gimme/versions/go1.10.5.linux.amd64/src/runtime/asm_amd64.s:2361
  | I0819 09:50:51.183915       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"kube-system", Name:"k1", UID:"b763fdec-c266-11e9-a2cb-0050568364d3", APIVersion:"v1", ResourceVersion:"622848", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "kube-system/k1"
  | panic: runtime error: invalid memory address or nil pointer dereference [recovered]
  | panic: runtime error: invalid memory address or nil pointer dereference
  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10194d1]
  |  
  | goroutine 109 [running]:
  | github.com/nmaupu/freenas-provisioner/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
  | /home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x107
  | panic(0x1178760, 0x1c108d0)
  | /home/travis/.gimme/versions/go1.10.5.linux.amd64/src/runtime/panic.go:502 +0x229
  | github.com/nmaupu/freenas-provisioner/provisioner.(*freenasProvisioner).Provision(0xc4200ac2c0, 0xc4200bf0d0, 0x6, 0xc420355530, 0x28, 0x0, 0x0, 0x0, 0xc4203b1da8, 0xc4200b7a40, ...)
  | /home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/provisioner/provisioner.go:243 +0x61
  | github.com/nmaupu/freenas-provisioner/vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller.(*ProvisionController).provisionClaimOperation(0xc4203ae4e0, 0xc4203b1da8, 0x1c23160, 0xc4204e14a0)
  | /home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller/controller.go:1014 +0xcf8
  | github.com/nmaupu/freenas-provisioner/vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller.(*ProvisionController).syncClaim(0xc4203ae4e0, 0x12d8220, 0xc4203b1da8, 0x12d8220, 0xc4203b1da8)
  | /home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller/controller.go:786 +0xaf
  | github.com/nmaupu/freenas-provisioner/vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller.(*ProvisionController).syncClaimHandler(0xc4203ae4e0, 0xc4204e14a0, 0xe, 0x11149a0, 0xc4205096b0)
  | /home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller/controller.go:759 +0x8d
  | github.com/nmaupu/freenas-provisioner/vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller.(*ProvisionController).processNextClaimWorkItem.func1(0xc4203ae4e0, 0x11149a0, 0xc4205096b0, 0x0, 0x0)
  | /home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller/controller.go:683 +0xe3
  | github.com/nmaupu/freenas-provisioner/vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller.(*ProvisionController).processNextClaimWorkItem(0xc4203ae4e0, 0xc4205c0201)
  | /home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller/controller.go:697 +0x55
  | github.com/nmaupu/freenas-provisioner/vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller.(*ProvisionController).runClaimWorker(0xc4203ae4e0)
  | /home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller/controller.go:657 +0x2b
  | github.com/nmaupu/freenas-provisioner/vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller.(*ProvisionController).(github.com/nmaupu/freenas-provisioner/vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller.runClaimWorker)-fm()
  | /home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller/controller.go:616 +0x2a
  | github.com/nmaupu/freenas-provisioner/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc4204392f0)
  | /home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
  | github.com/nmaupu/freenas-provisioner/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc4204392f0, 0x3b9aca00, 0x0, 0x20001, 0x0)
  | /home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbd
  | github.com/nmaupu/freenas-provisioner/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc4204392f0, 0x3b9aca00, 0x0)
  | /home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
  | created by github.com/nmaupu/freenas-provisioner/vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller.(*ProvisionController).Run.func1
  | /home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller/controller.go:616 +0x3e1

**Comment by travisghansen** [comment]
Can you describe the installation steps you followed? It appears to be failing to use the kubernetes API to retrieve the storage class which sounds like an rbac issue...or a missing storage class which would be extremely odd.

**Comment by gripenk** [comment]
I have the FreeNas on the same subnet.
Downloading the release v2.4.tgz
just following the readme, update the secret.yml (already base64 coded) and class.yml
using account with clusteradmin, running 

oc apply -f deploy/rbac.yaml -f deploy/deployment.yaml
oc apply -f deploy/secret.yaml -f deploy/class.yaml

The pod is up.

However, when I create a PV  with freenas-nfs, the pod crashes with the errors

**Comment by travisghansen** [comment]
Would you be comfortable trying to run the provisioner out of cluster? Basically delete the deployment (or scale it to 0) and then launch the binary from your workstation with an admin KUBECONFIG file exported.

I'm interested if the behavior is any different.

**Comment by gripenk** [comment]
I re-run as your suggestion but still fault. I wonder if my FreeNAS is not setup properly. I try to use "pool1" , "pool1/p1test1" without luck.

https://ibb.co/dG3w7n9

I0821 13:25:04.704958   97619 leaderelection.go:187] attempting to acquire leader lease  default/freenas.org-nfs...
I0821 13:25:20.491697   97619 leaderelection.go:196] successfully acquired lease default/freenas.org-nfs
I0821 13:25:20.492012   97619 controller.go:571] Starting provisioner controller freenas.org/nfs_freenas.local_080cbb66-c3d4-11e9-a327-005056830bfd!
I0821 13:25:20.492103   97619 event.go:221] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"default", Name:"freenas.org-nfs", UID:"6c7bf798-c3c8-11e9-ae2e-005056836813", APIVersion:"v1", ResourceVersion:"1114622", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' freenas.local_080cbb66-c3d4-11e9-a327-005056830bfd became leader
I0821 13:25:20.599244   97619 controller.go:620] Started provisioner controller freenas.org/nfs_freenas.local_080cbb66-c3d4-11e9-a327-005056830bfd!
I0821 13:25:44.359220   97619 controller.go:926] provision "kube-system/k6" class "freenas-nfs": started
I0821 13:25:44.363459   97619 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"kube-system", Name:"k6", UID:"1fac52c9-c3d4-11e9-ae2e-005056836813", APIVersion:"v1", ResourceVersion:"1114709", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "kube-system/k6"
E0821 13:25:44.363523   97619 runtime.go:69] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
/home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/home/travis/.gimme/versions/go1.10.5.linux.amd64/src/runtime/asm_amd64.s:573
/home/travis/.gimme/versions/go1.10.5.linux.amd64/src/runtime/panic.go:502
/home/travis/.gimme/versions/go1.10.5.linux.amd64/src/runtime/panic.go:63
/home/travis/.gimme/versions/go1.10.5.linux.amd64/src/runtime/signal_unix.go:388
/home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/provisioner/provisioner.go:243
/home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller/controller.go:1014
/home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller/controller.go:786
/home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller/controller.go:759
/home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller/controller.go:683
/home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller/controller.go:697
/home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller/controller.go:657
/home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller/controller.go:616
/home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/home/travis/.gimme/versions/go1.10.5.linux.amd64/src/runtime/asm_amd64.s:2361
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1018dc1]

goroutine 105 [running]:
github.com/nmaupu/freenas-provisioner/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x107
panic(0x1177580, 0x1c0f8a0)
        /home/travis/.gimme/versions/go1.10.5.linux.amd64/src/runtime/panic.go:502 +0x229
github.com/nmaupu/freenas-provisioner/provisioner.(*freenasProvisioner).Provision(0xc420355940, 0xc4202e9688, 0x6, 0xc4200171d0, 0x28, 0x0, 0x0, 0x0, 0xc42040a000, 0xc42047e210, ...)
        /home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/provisioner/provisioner.go:243 +0x61
github.com/nmaupu/freenas-provisioner/vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller.(*ProvisionController).provisionClaimOperation(0xc420261040, 0xc42040a000, 0x1c21b80, 0xc42003de50)
        /home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller/controller.go:1014 +0xcf8
github.com/nmaupu/freenas-provisioner/vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller.(*ProvisionController).syncClaim(0xc420261040, 0x12d7240, 0xc42040a000, 0x12d7240, 0xc42040a000)
        /home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller/controller.go:786 +0xaf
github.com/nmaupu/freenas-provisioner/vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller.(*ProvisionController).syncClaimHandler(0xc420261040, 0xc42003de50, 0xe, 0x11134c0, 0xc4202b0420)
        /home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller/controller.go:759 +0x8d
github.com/nmaupu/freenas-provisioner/vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller.(*ProvisionController).processNextClaimWorkItem.func1(0xc420261040, 0x11134c0, 0xc4202b0420, 0x0, 0x0)
        /home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller/controller.go:683 +0xe3
github.com/nmaupu/freenas-provisioner/vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller.(*ProvisionController).processNextClaimWorkItem(0xc420261040, 0xc420456350)
        /home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller/controller.go:697 +0x55
github.com/nmaupu/freenas-provisioner/vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller.(*ProvisionController).runClaimWorker(0xc420261040)
        /home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller/controller.go:657 +0x2b
github.com/nmaupu/freenas-provisioner/vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller.(*ProvisionController).(github.com/nmaupu/freenas-provisioner/vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller.runClaimWorker)-fm()
        /home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller/controller.go:616 +0x2a
github.com/nmaupu/freenas-provisioner/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc4203f3110)
        /home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
github.com/nmaupu/freenas-provisioner/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc4203f3110, 0x3b9aca00, 0x0, 0x1, 0x0)
        /home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbd
github.com/nmaupu/freenas-provisioner/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc4203f3110, 0x3b9aca00, 0x0)
        /home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/nmaupu/freenas-provisioner/vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller.(*ProvisionController).Run.func1
        /home/travis/gopath/src/github.com/nmaupu/freenas-provisioner/vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller/controller.go:616 +0x3e1

**Comment by travisghansen** [comment]
Pools is the screenshot look ok, although I noticed p1test1 had a child not created by the provisioner. I would recommend a dataset wholely dedicated to each storage class.


Regardless, from the stack trace I don't think it has anything to do with your server yet. It appears to puking on literally the very first line of code in the provision method which is supposed to get the storage class details from the kubernetes API.

Is there a hosted old 3.11 that I can do some testing on? Is it easy to build a test cluster without subscriptions etc?

Also, I'd be interested in knowing if you get the same error using the sister project here: https://github.com/travisghansen/freenas-iscsi-provisioner

**Comment by gripenk** [comment]
It is a cluster (development use) hosted in the University. However, the access is limited. 

I also test freenas-iscsi-provisioner but still fails :<

I0822 04:25:25.843144       1 controller.go:615] Starting provisioner controller dd4b5061-c494-11e9-a8d5-0a580a82020c!
I0822 04:25:25.843273       1 controller.go:652] Started provisioner controller dd4b5061-c494-11e9-a8d5-0a580a82020c!
I0822 04:25:25.866895       1 leaderelection.go:156] attempting to acquire leader lease...
I0822 04:25:42.403669       1 leaderelection.go:178] successfully acquired lease to provision for pvc kube-system/q1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xfb56bc]

goroutine 106 [running]:
github.com/travisghansen/freenas-iscsi-provisioner/provisioner.(*freenasProvisioner).Provision(0xc00039afe0, 0xc00048c7fa, 0x6, 0xc00014f740, 0x28, 0x0, 0x0, 0x0, 0xc0002d41a0, 0xc000209b90, ...)
	/home/travis/gopath/src/github.com/travisghansen/freenas-iscsi-provisioner/provisioner/provisioner.go:319 +0xbc
github.com/travisghansen/freenas-iscsi-provisioner/vendor/github.com/kubernetes-incubator/external-storage/lib/controller.(*ProvisionController).provisionClaimOperation(0xc00047a000, 0xc0002d41a0, 0x1f44060, 0xc0004aefc0)
	/home/travis/gopath/src/github.com/travisghansen/freenas-iscsi-provisioner/vendor/github.com/kubernetes-incubator/external-storage/lib/controller/controller.go:1066 +0xdf2
github.com/travisghansen/freenas-iscsi-provisioner/vendor/github.com/kubernetes-incubator/external-storage/lib/controller.(*ProvisionController).lockProvisionClaimOperation.func1(0xc000170180)
	/home/travis/gopath/src/github.com/travisghansen/freenas-iscsi-provisioner/vendor/github.com/kubernetes-incubator/external-storage/lib/controller/controller.go:935 +0x76
created by github.com/travisghansen/freenas-iscsi-provisioner/vendor/github.com/kubernetes-incubator/external-storage/lib/leaderelection.(*LeaderElector).Run
	/home/travis/gopath/src/github.com/travisghansen/freenas-iscsi-provisioner/vendor/github.com/kubernetes-incubator/external-storage/lib/leaderelection/leaderelection.go:129 +0xad

**Comment by travisghansen** [comment]
Wow same method. Can you do a `describe` on the PVC and put the yaml here?

**Comment by gripenk** [comment]
As i don't modify the rbac.yaml and deployment.yaml, i posted other yaml here

== secret.yaml ==
---
apiVersion: v1
kind: Secret
metadata:
  name: freenas-nfs
  namespace: kube-system
type: Opaque
data:
  # all values should be base64 encoded (ie: echo -n 'https' | base64)
  #
  # note that all values are relative to where the provisioner is running
  # ie: if running the provisioner directly on the FreeNAS server 'localhost'
  # would be a valid 'host' value

  # http|https
  # default: http
  #protocol:
  protocol: "aHR0cHM="

  # default: localhost (for running the provisioner out of cluster directly on FreeNAS node)
  #host:
  host: "MTAuNjQuMjQ4LjI0OA=="

  # default: 80
  #port:
  port: "NDQz"

  # default: root (api is only available for root currently)
  #username:
  password: "XXXXXXXXX"                    <== masked

  # allow for self-signed/untrusted certs if using https
  # true|false
  # default: false
  #allowInsecure:
  allowInsecure: "dHJ1ZQ=="

=====  class.yaml =====
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: freenas-nfs
provisioner: freenas.org/nfs
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  datasetParentName: "pool1/p1test1"
  datasetEnableQuotas: "true"
  datasetNamespaceQuota: "10G"

====================================

oc describe pvc q5 -n kube-system
Name:          q5
Namespace:     kube-system
StorageClass:  freenas-nfs
Status:        Pending
Volume:
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-class=freenas-nfs
               volume.beta.kubernetes.io/storage-provisioner=freenas.org/nfs
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
Events:
  Type    Reason                Age               From                                                                                           Message
  ----    ------                ----              ----                                                                                           -------
  Normal  Provisioning          2m                freenas.org/nfs_freenas-nfs-provisioner-597d5b54ff-d4v8d_e76fe95b-c4bd-11e9-bdcb-0a580a82020d  External provisioner is provisioning volume for claim "kube-system/q5"
  Normal  Provisioning          1m                freenas.org/nfs_freenas-nfs-provisioner-597d5b54ff-d4v8d_1028ccb9-c4be-11e9-95fe-0a580a82020d  External provisioner is provisioning volume for claim "kube-system/q5"
  Normal  ExternalProvisioning  9s (x11 over 2m)  persistentvolume-controller                                                                    waiting for a volume to be created, either by external provisioner "freenas.org/nfs" or manually created by system administrator

**Comment by travisghansen** [comment]
I'm going to try to setup an okd cluster and see what I get.

**Comment by travisghansen** [comment]
If you want to share your installation method so I can mimic as close as possible that would be great.

**Comment by gripenk** [comment]
I have 9 VMs for 1 OKD cluster. The VMs are pre-configured CentOS 7 and I use openshift-ansible (https://github.com/openshift/openshift-ansible) to install the OKD 3.11 . 

I don't know if it is easy for you to setup such cluster or not. Maybe you can try to use this single host inventory example (https://github.com/openshift/openshift-ansible/blob/release-3.11/inventory/hosts.localhost).
Or you may try to use minishift first. (https://www.okd.io/minishift/)

**Comment by travisghansen** [comment]
Yeah, I've got resources so I'll see what I can do. I'll probably ask in the storage slack channel of anyone has seen it before with openshift.

Depending on the answer to that I may just say hold off a bit as I'm putting together a new setup with csi which will support the full suite of features (resize, snaps, clones, etc)...you can be one of the first testers :)

My code for the new one is quite blown up but the basics are already in place and I have resize, create, delete, etc already completed. I'm making it relatively generic so it'll work with other basic NAS systems especially zfs based but it should function fine with btrfs and stratis based systems as well.

**Comment by gripenk** [comment]
FYI
I  used nfs-client provisioner (https://github.com/kubernetes-incubator/external-storage/tree/master/nfs-client#without-helm) which can provision PV on OKD.

**Comment by gripenk** [comment]
i cannot get such log
here is my output

I0826 16:16:41.844471       1 leaderelection.go:185] attempting to acquire leader lease  default/fuseim.pri-ifs...
I0826 16:16:41.857429       1 leaderelection.go:194] successfully acquired lease default/fuseim.pri-ifs
I0826 16:16:41.857975       1 controller.go:631] Starting provisioner controller fuseim.pri/ifs_nfs-client-provisioner-64666c946b-cgcjp_e3d386eb-c81c-11e9-8998-0a580a830217!
I0826 16:16:41.858077       1 event.go:221] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"default", Name:"fuseim.pri-ifs", UID:"e3d43d9b-c81c-11e9-af03-005056837f20", APIVersion:"v1", ResourceVersion:"2447830", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' nfs-client-provisioner-64666c946b-cgcjp_e3d386eb-c81c-11e9-8998-0a580a830217 became leader
I0826 16:16:41.958174       1 controller.go:680] Started provisioner controller fuseim.pri/ifs_nfs-client-provisioner-64666c946b-cgcjp_e3d386eb-c81c-11e9-8998-0a580a830217!
I0826 16:22:49.259487       1 controller.go:987] provision "default/w1" class "managed-nfs-storage": started
I0826 16:22:49.269565       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"w1", UID:"bec24859-c81d-11e9-af03-005056837f20", APIVersion:"v1", ResourceVersion:"2449054", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/w1"
I0826 16:22:49.271714       1 controller.go:1087] provision "default/w1" class "managed-nfs-storage": volume "pvc-bec24859-c81d-11e9-af03-005056837f20" provisioned
I0826 16:22:49.271741       1 controller.go:1101] provision "default/w1" class "managed-nfs-storage": trying to save persistentvvolume "pvc-bec24859-c81d-11e9-af03-005056837f20"
I0826 16:22:49.305071       1 controller.go:1108] provision "default/w1" class "managed-nfs-storage": persistentvolume "pvc-bec24859-c81d-11e9-af03-005056837f20" saved
I0826 16:22:49.305121       1 controller.go:1149] provision "default/w1" class "managed-nfs-storage": succeeded
I0826 16:22:49.305382       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"w1", UID:"bec24859-c81d-11e9-af03-005056837f20", APIVersion:"v1", ResourceVersion:"2449054", FieldPath:""}): type: 'Normal' reason: 'ProvisioningSucceeded' Successfully provisioned volume pvc-bec24859-c81d-11e9-af03-005056837f20

**Comment by travisghansen** [comment]
Just a follow-up here, I've had a chance to work on the csi driver a bit more and have made good progress. I've fully implemented all the 'controller' functionality of the driver (nfs vs iscsi only currently) including snapshots, clones and resizing. I need to shift focus to the 'node' side of the equation now which includes work on handling the actual mounting etc. After that I'll work on packaging etc to make it easy to deploy and then testers will be welcome :)

My guess is that's still 2-3 weeks before everything is fleshed out enough and documented. My intent is to have iscsi implemented simultaneously but we'll see how it goes.

**Comment by travisghansen** [comment]
OK, made some good progress here over the last couple weeks and now have a fully implemented csi driver for nfs (no packaging yet...will be via helm).

I'm interested in some feedback though..the latest spec introduces 2 new ideas:

1. snapshots
2. creating a volume from either a snapshot or another volume

I've been told that from kubernetes the expectation is that a snapshot's life is independent of the volume the snapshot was taken from...also, same is true for a volume cloned from another volume.

This is kinda counter-intuitive to how zfs works and I'm wondering what behavior folks *want* independent of the theory behind the spec.

Do you want the space savings to make clones without being able to delete the parent unless dependents/descendants are gone as well (tradeoff would be space savings...at least at the beginning)?

or

Do you want the freedom associated with having completely independent entities with the cost of replicating data?

I'm torn.

**Comment by travisghansen** [comment]
In practice the difference is `zfs clone` vs `zfs send ... | zfs receive ...`

**Comment by travisghansen** [comment]
Also to note, I've not created an iscsi driver yet, but I have implemented most/all of the session management and other tools needed to make it function (ie: formatting filesystems, running fsck, expanding filesystems, etc). I think fully implementing the driver will be relatively easy once a few questions floating around get answered..
