### ISSUE TITLE
Update your readme or class.yaml comments for FreeNas 11.3

### ISSUE THREAD

**Issue by Shifter2600** [nmaupu/freenas-provisioner#37]
For FreeNas 11.3 I needed to change these 2 values in the class.
`datasetEnableQuotas: 'false'`
`datasetEnableReservation: 'false'`

With out this change I would receive this error;
Warning  ProvisioningFailed    15s (x2 over 30s)  freenas.org/nfs_freenas-nfs-provisioner-7769df7f96-5wnwf_63dd7f68-9c3f-11ea-b0bc-0a468e8acd9a  failed to provision volume with StorageClass "freenas-nfs": Error creating dataset "tank/default/freenas-test-pvc" - message: {"refquota":["Specify the value with IEC suffixes, e.g. 10 GiB"],"refreservation":["Specify the value with IEC suffixes, e.g. 10 GiB"]}, status: 400

**Comment by travisghansen** [comment]
That was fixed some time back. Are you on the latest version of the provisioner?

**Comment by Shifter2600** [comment]
I just set things up yesterday so everything would be current.
I used the default yaml files you had in Deploy all as is excluding the simple changes in the secret.yaml.
My freenas version is 11.3-U3.1 which is the latest as of this post.
My pool is named tank and the default would get created but result in the error above when it tried to create the Share.

**Comment by Shifter2600** [comment]
Found the issue in your deployment.yaml you have your image version specified to 2.4 i see you are now on 2.6 I'll update the image.
    spec:
      serviceAccountName: freenas-nfs-provisioner
      containers:
        - name: freenas-nfs-provisioner
          image: docker.io/nmaupu/freenas-provisioner:2.4 <<<<

**Comment by travisghansen** [comment]
Yeah oops :( as an FYI this project is essentially in maintenance mode. If you’re starting fresh I recommend https://github.com/democratic-csi/democratic-csi

**Comment by Shifter2600** [comment]
I think I will stick with this since the documentation on your other project isn't too extensive. 
I'm using k3os k3s so pretty basic and only need a basic NSF integration with FreeNas.  I'm still learning myself and I can follow the yaml's you have in this project.

**Comment by travisghansen** [comment]
Fair enough. If you’re familiar with helm the samples here should be enough to get you going: https://github.com/democratic-csi/charts

Much of it is the same as this project.

**Comment by Shifter2600** [comment]
Looks like I may need to force myself over to your new project because I am getting a new error on this one using the new image.
 Warning  ProvisioningFailed    3s (x4 over 49s)  freenas.org/nfs_freenas-nfs-provisioner-647674fd9d-h6vmd_74310727-9c85-11ea-a372-86d997d2826e  failed to provision volume with StorageClass "freenas-nfs": Error creating dataset "tank/default/freenas-test-pvc" - message: {"refquota":["Should be greater or equal than 1073741824 or Should be 0"]}, status: 400

**Comment by travisghansen** [comment]
That seems pretty odd for sure :(

Sometimes the FreeNAS API is a mess and they love to introduce ‘fixes’ that break compatibility with older releases. The new project does nearly 100% of its operations over ssh eliminating that garbage altogether while also providing a much stronger/larger feature set in terms of what can be done with zfs. Aside from that it implements the csi spec for k8s which itself is also much more powerful and has advanced features such as volume expansion and snapshots etc (all of which I implemented).

I’m happy to help you get going with it if you want.

I often find folks who use FreeNAS are also using pfSense. If you are I have a controller for that as well.

**Comment by Shifter2600** [comment]
K I will check to you over on the other project. I already have Helm installed and your repo added.

**Comment by mattmattox** [comment]
@travisghansen Try changing deploy/test-claim.yaml to a larger size like 10G

Example:
```
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: freenas-test-pvc
spec:
  storageClassName: freenas-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10G
```
