### ISSUE TITLE
doesn't work at all

### ISSUE THREAD

**Issue by inmanturbo** [nmaupu/freenas-provisioner#47]
nothing happens. I follow directions in readme and and all I get is pending forever volume claim. No traffic between freenas and kubernetes node.

**Comment by travisghansen** [comment]
Do you have any logs?

You may consider an alternative over here: https://github.com/democratic-csi/democratic-csi

It’s csi based (how k8s does storage now) and I’m actively working on it.

**Comment by inmanturbo** [comment]
No, nothing of consequence is logged. Mainly because there are no errors. Everything appears successful, there's just no action. `kubectl` and dashboard show the storage class is there and appears fine, the test persistent volume claim shows pending with no errors, and yet no requests are sent to the Freenas server. However my secret is showing up in the dashboard, perhaps I didn't apply this correctly. 

But after filling in the needed values in `deploy/secret.yaml`  with the output from `echo -n 'secretvalue' | base64` and then executing `kubectl apply -f deploy/secret.yaml -f deploy/class.yaml`, I got back no errors.

Thanks for the alternative suggestion. I'll have a look at it.

**Comment by travisghansen** [comment]
Perhaps you altered the storage class name and the pvc class isn’t the same?

**Comment by inmanturbo** [comment]
Thank you for your help. I'm closing this as there's not much here that's likely to help anyone else and I'm now using the alternative you suggested, https://github.com/democratic-csi/democratic-csi.
