### ISSUE TITLE
unexpected error getting claim reference: selfLink was empty, can't make reference

### ISSUE THREAD

**Issue by schnable** [nmaupu/freenas-provisioner#49]
It looks like newer Kubernetes (1.20 / 1.21) have deprecated selflinks and this mandates a code change in NFS provisioners.  See this issue for details: https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/issues/25.

I was able to work around this for now using the - --feature-gates=RemoveSelfLink=false  work around mentioned there, but this isn't a long term solution.

**Comment by schnable** [comment]
(I see there are a few code changes since the v2.6 release - some to support 1.20.X - perhaps I just need a rebuild?  I will try that...)

**Comment by travisghansen** [comment]
It has been fixed but it looks like a new release was never made.

**Comment by nmaupu** [comment]
My bad:
https://github.com/nmaupu/freenas-provisioner/releases/tag/v2.7
